[package]
name = "blazy"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }
